### ISSUE TITLE
Taking into account number of channels in the '_interpolate' function

### ISSUE THREAD

**Issue by victoriamazo** [alwynmathew/bilinear-sampler-pytorch#2]
Hi!
Thank you for the code. There is one small correction at the end of the '_interpolate' function - transformed image should be of the same shape as the input image (with the same number of channels), therefore the last lines in the function should be
```
im_flat = im.contiguous().view(-1, _num_channels)
pix_l = torch.gather(im_flat, 0, idx_l.repeat(_num_channels).view(-1, _num_channels))
pix_r = torch.gather(im_flat, 0, idx_r.repeat(_num_channels).view(-1, _num_channels)) 
```
to get the correct transformed image and the rest is the same.

**Comment by alwynmathew** [comment]
Thank you @victoriamazo for pointing it out.
